{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPW915cCSdn1BefBYUR0mxS",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/kavyatalam08/assignment3/blob/main/EmployeeDashboard.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "#                 EMPLOYEE PAYROLL DASHBOARD\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "st.title(\"💼 Employee Payroll Dashboard\")\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# Employee : Rahul Sharma\n",
        "# Department : Analytics\n",
        "# Designation : Data Analyst\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "st.header(\"Employee Information\")\n",
        "st.write(\"**Employee :** Rahul Sharma\")\n",
        "st.write(\"**Department :** Analytics\")\n",
        "st.write(\"**Designation :** Data Analyst\")\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# Gross Salary     Net Salary     Deductions     Paid Days\n",
        "# ₹105,000         ₹95,000         ₹10,000          31\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "col1, col2, col3, col4 = st.columns(4)\n",
        "\n",
        "col1.metric(\"Gross Salary\", \"₹105,000\")\n",
        "col2.metric(\"Net Salary\", \"₹95,000\")\n",
        "col3.metric(\"Deductions\", \"₹10,000\")\n",
        "col4.metric(\"Paid Days\", \"31\")\n",
        "\n",
        "st.divider()\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# Salary Components (Bar Chart)\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "salary = pd.DataFrame({\n",
        "    \"Component\": [\"Basic Salary\", \"HRA\", \"Medical\", \"Special Allowance\", \"Bonus\"],\n",
        "    \"Amount\": [60000, 24000, 4000, 9000, 5000]\n",
        "})\n",
        "\n",
        "st.subheader(\"Salary Components (Bar Chart)\")\n",
        "\n",
        "fig, ax = plt.subplots()\n",
        "ax.bar(salary[\"Component\"], salary[\"Amount\"])\n",
        "plt.xticks(rotation=20)\n",
        "st.pyplot(fig)\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# Earnings Distribution (Pie Chart)\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "st.subheader(\"Earnings Distribution (Pie Chart)\")\n",
        "\n",
        "fig, ax = plt.subplots()\n",
        "ax.pie(\n",
        "    salary[\"Amount\"],\n",
        "    labels=salary[\"Component\"],\n",
        "    autopct=\"%1.1f%%\",\n",
        "    startangle=90\n",
        ")\n",
        "ax.axis(\"equal\")\n",
        "st.pyplot(fig)\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# Gross vs Deduction vs Net (Bar Chart)\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "st.subheader(\"Gross vs Deduction vs Net (Bar Chart)\")\n",
        "\n",
        "fig, ax = plt.subplots()\n",
        "ax.bar(\n",
        "    [\"Gross\", \"Deduction\", \"Net\"],\n",
        "    [105000, 10000, 95000]\n",
        ")\n",
        "st.pyplot(fig)\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# Employee Details\n",
        "# Bank Name\n",
        "# Account Number\n",
        "# PAN\n",
        "# Joining Date\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "st.subheader(\"Employee Details\")\n",
        "\n",
        "details = pd.DataFrame({\n",
        "    \"Field\": [\n",
        "        \"Bank Name\",\n",
        "        \"Account Number\",\n",
        "        \"PAN\",\n",
        "        \"Joining Date\"\n",
        "    ],\n",
        "    \"Value\": [\n",
        "        \"State Bank of India\",\n",
        "        \"123456789012\",\n",
        "        \"ABCDE1234F\",\n",
        "        \"15-Jan-2023\"\n",
        "    ]\n",
        "})\n",
        "\n",
        "st.table(details)"
      ],
      "metadata": {
        "id": "KQ-IYaIx0pLB"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}