{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPy1mYU2HOx4EHpOGYBzkhJ",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/kavyatalam08/assignment3/blob/main/StudentDashboard.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "# -------------------------------\n",
        "# Dashboard Title\n",
        "# -------------------------------\n",
        "st.title(\"🎓 Student Performance Dashboard\")\n",
        "\n",
        "# -------------------------------\n",
        "# Student Information\n",
        "# -------------------------------\n",
        "st.header(\"Student Information\")\n",
        "\n",
        "st.write(\"**Student Name:** Rahul Sharma\")\n",
        "st.write(\"**Roll Number:** 23DS101\")\n",
        "st.write(\"**Class:** B.Tech CSE-DS Final Year\")\n",
        "\n",
        "# -------------------------------\n",
        "# KPI Cards\n",
        "# -------------------------------\n",
        "col1, col2, col3, col4 = st.columns(4)\n",
        "\n",
        "col1.metric(\"Total Marks\", \"540\")\n",
        "col2.metric(\"Percentage\", \"90%\")\n",
        "col3.metric(\"Attendance\", \"95%\")\n",
        "col4.metric(\"Rank\", \"2\")\n",
        "\n",
        "st.divider()\n",
        "\n",
        "# -------------------------------\n",
        "# Subject-wise Marks\n",
        "# -------------------------------\n",
        "marks = pd.DataFrame({\n",
        "    \"Subject\": [\n",
        "        \"Python\",\n",
        "        \"DBMS\",\n",
        "        \"Java\",\n",
        "        \"AI\",\n",
        "        \"ML\",\n",
        "        \"Cloud\"\n",
        "    ],\n",
        "    \"Marks\": [\n",
        "        95,\n",
        "        88,\n",
        "        92,\n",
        "        90,\n",
        "        85,\n",
        "        90\n",
        "    ]\n",
        "})\n",
        "\n",
        "st.subheader(\"Subject-wise Marks (Bar Chart)\")\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(7,4))\n",
        "\n",
        "ax.bar(marks[\"Subject\"], marks[\"Marks\"])\n",
        "\n",
        "ax.set_xlabel(\"Subjects\")\n",
        "ax.set_ylabel(\"Marks\")\n",
        "ax.set_ylim(0,100)\n",
        "\n",
        "st.pyplot(fig)\n",
        "\n",
        "st.divider()\n",
        "\n",
        "# -------------------------------\n",
        "# Marks Distribution\n",
        "# -------------------------------\n",
        "st.subheader(\"Marks Distribution (Pie Chart)\")\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(6,6))\n",
        "\n",
        "ax.pie(\n",
        "    marks[\"Marks\"],\n",
        "    labels=marks[\"Subject\"],\n",
        "    autopct=\"%1.1f%%\",\n",
        "    startangle=90\n",
        ")\n",
        "\n",
        "st.pyplot(fig)\n",
        "\n",
        "st.divider()\n",
        "\n",
        "# -------------------------------\n",
        "# Attendance Trend\n",
        "# -------------------------------\n",
        "st.subheader(\"Attendance Trend (Line Chart)\")\n",
        "\n",
        "attendance = pd.DataFrame({\n",
        "    \"Month\": [\n",
        "        \"Jan\",\n",
        "        \"Feb\",\n",
        "        \"Mar\",\n",
        "        \"Apr\",\n",
        "        \"May\",\n",
        "        \"Jun\"\n",
        "    ],\n",
        "    \"Attendance\": [\n",
        "        90,\n",
        "        92,\n",
        "        94,\n",
        "        95,\n",
        "        96,\n",
        "        95\n",
        "    ]\n",
        "})\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(7,4))\n",
        "\n",
        "ax.plot(\n",
        "    attendance[\"Month\"],\n",
        "    attendance[\"Attendance\"],\n",
        "    marker=\"o\"\n",
        ")\n",
        "\n",
        "ax.set_xlabel(\"Month\")\n",
        "ax.set_ylabel(\"Attendance (%)\")\n",
        "ax.set_ylim(80,100)\n",
        "\n",
        "st.pyplot(fig)\n",
        "\n",
        "st.divider()\n",
        "\n",
        "# -------------------------------\n",
        "# Student Details\n",
        "# -------------------------------\n",
        "st.subheader(\"Student Details Table\")\n",
        "\n",
        "details = pd.DataFrame({\n",
        "    \"Field\": [\n",
        "        \"Department\",\n",
        "        \"Section\",\n",
        "        \"Semester\",\n",
        "        \"Academic Year\",\n",
        "        \"College\"\n",
        "    ],\n",
        "    \"Value\": [\n",
        "        \"CSE-Data Science\",\n",
        "        \"A\",\n",
        "        \"8th\",\n",
        "        \"2025-26\",\n",
        "        \"XYZ Engineering College\"\n",
        "    ]\n",
        "})\n",
        "\n",
        "st.table(details)"
      ],
      "metadata": {
        "id": "YxocVNQfdyCU"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}
